### ISSUE TITLE
down?

### ISSUE THREAD

**Issue by damnms** [mathewmeconry/TV7_EPG_Data#6] opened 2021-01-08 19:20 UTC
i have no EPG data - is something broken? do you get emails when the state is "failed" on the front page?

**Comment by walserc** [comment] 2021-01-12 19:49
The last successful days export seems to be from 2021-01-01...

**Comment by nbarrientos** [comment] 2021-01-12 22:14
The parser is crashing in the scheduled Circleci [job that fetches new EPG data](https://github.com/mathewmeconry/TV7_EPG_Parser/blob/master/.circleci/config.yml#L59) and pushes it to this repository.

https://app.circleci.com/pipelines/github/mathewmeconry/TV7_EPG_Parser/318/workflows/c2ac58e0-6e1c-4cfa-8cfd-777299be7521/jobs/1075

![image](https://user-images.githubusercontent.com/131893/104380557-78964200-552b-11eb-972b-2b2782ef8707.png)

Judging from the exception, perhaps the data format returned by `tele.ch` has changed.

The last successful job dates from the 1st of January:

https://app.circleci.com/pipelines/github/mathewmeconry/TV7_EPG_Parser/307/workflows/152936d5-8fbc-4288-bd54-231803069dbd

**Comment by nbarrientos** [comment] 2021-01-12 22:15
Maybe it's better to open an issue here:

https://github.com/mathewmeconry/TV7_EPG_Parser/

And add a link to this one.

**Comment by mathewmeconry** [comment] 2021-01-13 08:48
Hi guys
Sorry I completely missed the notification for this issue...
Tele.ch is not publishing the EPG data anymore online and redirects all requests to their shop page. 
Unfortunately, the parser failed because of this and didn't update the data.

Thanks to @x-jokay who provided a pull with a fix. 

The parser is currently running and should update the new EPG Data in a few minutes.
Sorry for the inconvenience

**Comment by mathewmeconry** [comment] 2021-01-13 09:23
So the files are updated and code fixed. 
The xml file looks good and the import of it worked.
I close this issue now

**Closed as completed by mathewmeconry** 2021-01-13 09:23 UTC

**Comment by nbarrientos** [comment] 2021-01-13 09:38
Sweet, thanks both :)

**Comment by walserc** [comment] 2021-01-13 09:51
Thanks for the quick reaction, I will test it tonight on my Kodi installation!

**Comment by mathewmeconry** [comment] 2021-01-13 14:08
> Thanks for the quick reaction, I will test it tonight on my Kodi installation!

Please let me know if it works or not. The matching rate only went down by 2 channels from 143 to 141...

**Comment by jokay** [comment] 2021-01-13 14:52
@mathewmeconry I can confirm it works 👍🏼
