### ISSUE TITLE
XML not valid

### ISSUE THREAD

**Issue by marwin79** [mathewmeconry/TV7_EPG_Data#13] opened 2023-08-16 06:11 UTC
Looks like XML is broken.

```
[root@fedora2 bin]# wget -q https://github.com/mathewmeconry/TV7_EPG_Data/raw/master/tv7_epg.xml.gz
[root@fedora2 bin]# gunzip tv7_epg.xml.gz
[root@fedora2 bin]# xmllint --format tv7_epg.xml > tv7_epg.xml.new
tv7_epg.xml:1: parser error : attributes construct error
t/media/logos/Alarabiya.png" /></channel><programme start="20230815195800 +0200"
                                                                               ^
tv7_epg.xml:1: parser error : Couldn't find end of Start Tag programme line 1
t/media/logos/Alarabiya.png" /></channel><programme start="20230815195800 +0200"
                                                                               ^
tv7_epg.xml:1: parser error : Opening and ending tag mismatch: tv line 1 and programme
624f2bc51d4173c2966759c13e5e9.jpg" /><title>This is Cbeebies</title></programme>
                                                                               ^
tv7_epg.xml:1: parser error : Extra content at the end of the document
624f2bc51d4173c2966759c13e5e9.jpg" /><title>This is Cbeebies</title></programme>
                                                                               ^
```

Could that be related to the change in the parser two days ago?

**Comment by jokay** [comment] 2023-08-16 06:33
We are getting this when trying to parse it.

```sh
'stop' is an unexpected token. Expecting whitespace. Line 1, position 46131.
```

**Comment by marwin79** [comment] 2023-08-16 18:39
I can fix the file with
```
gunzip tv7_epg.xml.gz
sed -i 's/"stop="/" stop="/g' tv7_epg.xml
```

Will make a merge request soon.

**Comment by rbkn** [comment] 2023-08-18 10:05
@marwin79  Have just made a merge request in the parser repo.  
https://github.com/mathewmeconry/TV7_EPG_Parser/pull/33

Not sure whether this is a duplicate of yours.

**Comment by mathewmeconry** [comment] 2023-08-21 13:04
Sorry that it took me so long... Pull is merged and new workflow is triggered. let's see if it fixes ist

**Comment by rbkn** [comment] 2023-08-21 13:52
Looks like the fix worked for me - EPG data showing nicely again.

**Comment by mathewmeconry** [comment] 2023-08-22 06:42
:+1: then I close the issue :)

**Closed as completed by mathewmeconry** 2023-08-22 06:42 UTC
